version: '3'

services:
  vue-frontend:
    image: migisapp/frontend-vue:1.02
    container_name: container_name
    restart: unless-stopped
    tty: true
    working_dir: /usr/share/nginx/html
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - ./config/frontend-vue/nginx.conf:/etc/nginx/conf.d/default.conf